export const CHANGE_THEME = 'CHANGE THEME'
export const CHANGE_EVENTS = "CHANGE_EVENTS"
export const CHANGE_GROUP = "CHANGE_GROUP"
export const PERSONS_FETCH_DATA_SUCCESS = "PERSONS_FETCH_DATA_SUCCESS"